packages:
  - .
  - functions

autoInstallPeers: true
allowBuilds:
  "@firebase/util": true
  "@parcel/watcher": true
  protobufjs: true
  re2: true
  unrs-resolver: true
overrides:
  '@opentelemetry/core@<2.8.0': ^2.8.0
  csv-parse@<7.0.2: ^7.0.2
  ts-deepmerge@<8.0.0: ^8.0.0
  uuid@<11.1.1: ^11.1.1
