packages:
  - .
  - functions

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
  - re2
  - unrs-resolver

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  '@modelcontextprotocol/sdk@>=1.10.0 <=1.25.3': '>=1.26.0'
  ajv@<6.14.0: '>=6.14.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  diff@<4.0.4: '>=4.0.4'
  fast-xml-parser@>=4.1.3 <5.3.5: '>=5.3.5'
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  hono@<4.11.10: '>=4.11.10'
  hono@<4.11.7: '>=4.11.7'
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=5.0.0 <5.1.7: '>=5.1.7'
  minimatch@>=6.0.0 <6.2.1: '>=6.2.1'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.3: '>=7.5.4'
